version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-230-231-71.compute-1.amazonaws.com
            database: d17a3rgg6sdefc
            user: enntifkeujldub
            password: b9029aa3c71bde1ba4fba6c1fa1832ec8e0441bd468f2252e52c8b660df94f1b
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true